import rawFixtures from '../data/fixtures.json'
import rawMeta from '../data/meta.json'
import { fixturesFileSchema, metaSchema, type Fixture } from './schema'
import { competitionRank, type CompetitionKey } from './competitions'
import { brooklynDate, hoursSince, syncStamp, zonedParts } from './time'
import { BROOKLYN_TZ } from './competitions'

/**
 * Fixture data is validated once at module load. It is generated by `npm run sync`, so a
 * schema failure here means the generator and the app have drifted apart — better to fail
 * loudly at startup than to render half-understood rows.
 */
export const FIXTURES: Fixture[] = fixturesFileSchema.parse(rawFixtures)
export const META = metaSchema.parse(rawMeta)

/**
 * Fixtures are grouped by their *Brooklyn* calendar date, not the stadium's. A 21:00 kickoff
 * in Rome on a Wednesday is still Wednesday evening in Brooklyn, but a 00:30 CET kickoff is
 * the previous day — and the day Beni plans around is his own.
 */
export const BY_DATE: ReadonlyMap<string, Fixture[]> = (() => {
  const map = new Map<string, Fixture[]>()
  for (const f of FIXTURES) {
    const key = brooklynDate(f.kickoffUtc)
    const list = map.get(key)
    if (list) list.push(f)
    else map.set(key, [f])
  }
  for (const list of map.values()) sortForDisplay(list)
  return map
})()

/** Trophies first, then European cups, then domestic leagues; earliest kickoff first within a tier. */
export function sortForDisplay(list: Fixture[]): Fixture[] {
  return list.sort(
    (a, b) =>
      competitionRank(a.competition) - competitionRank(b.competition) ||
      a.kickoffUtc.localeCompare(b.kickoffUtc),
  )
}

export function fixturesOn(date: string, active: ReadonlySet<CompetitionKey>): Fixture[] {
  return (BY_DATE.get(date) ?? []).filter((f) => active.has(f.competition))
}

/** Total on a date regardless of filters — lets the UI say "hidden by filters" vs "nothing on". */
export function totalOn(date: string): number {
  return BY_DATE.get(date)?.length ?? 0
}

/**
 * The one gate for "not yet kicked off", shared by every hero (v0.2.2): Ledger's Next-up
 * strip through `upcoming`, Poster's Tonight's slate through `planSlate`. Two heroes with two
 * clocks was the bug (docs/v0.3.0-ideas.md row 3); two copies of one gate would be the same
 * bug in disguise. Scheduled only — a postponed or cancelled match has no honest kickoff to
 * promise, and an in-play match (a snapshot's or a real one) has kicked off. A league-set
 * time must still be ahead of `nowUtcIso`, so a fixture drops out at its kickoff minute; a
 * placeholder (TBC) time is trusted only to the day and is never evicted by arithmetic on an
 * instant the league never set — the caller's date filter is what retires it.
 */
export function stillToKickOff(f: Fixture, nowUtcIso: string): boolean {
  return f.status === 'scheduled' && (f.timeConfidence !== 'exact' || f.kickoffUtc > nowUtcIso)
}

/** Kickoffs still ahead from `fromDate` on, earliest first — see stillToKickOff. */
export function upcoming(
  fromDate: string,
  nowUtcIso: string,
  active: ReadonlySet<CompetitionKey>,
  limit: number,
  fixtures: readonly Fixture[] = FIXTURES,
): Fixture[] {
  return fixtures
    .filter(
      (f) =>
        stillToKickOff(f, nowUtcIso) &&
        brooklynDate(f.kickoffUtc) >= fromDate &&
        active.has(f.competition),
    )
    .sort((a, b) => a.kickoffUtc.localeCompare(b.kickoffUtc))
    .slice(0, limit)
}

/** The next date after `fromDate` with at least one fixture surviving the filters. */
export function nextMatchday(
  fromDate: string,
  active: ReadonlySet<CompetitionKey>,
  fixtures: readonly Fixture[] = FIXTURES,
): string | null {
  let best: string | null = null
  for (const f of fixtures) {
    if (!active.has(f.competition)) continue
    const d = brooklynDate(f.kickoffUtc)
    if (d > fromDate && (best === null || d < best)) best = d
  }
  return best
}

/**
 * What Poster's hero shows, decided here so the component decides nothing about time:
 * tonight's slate — today's fixtures still to kick off, in kickoff order — while there is
 * one; otherwise the next matchday's scheduled fixtures, and `isTonight: false` so the hero
 * says so ("Next matchday — nothing left today", `MATCHES` not `REMAINING`). The flip is
 * clock-driven: it happens at the last kickoff, not at the next snapshot. `date` is null
 * only when nothing at all is ahead under the filters.
 */
export function planSlate(
  today: string,
  nowUtcIso: string,
  active: ReadonlySet<CompetitionKey>,
  fixtures: readonly Fixture[] = FIXTURES,
): { date: string | null; slate: Fixture[]; isTonight: boolean } {
  const on = (date: string) =>
    fixtures
      .filter(
        (f) =>
          brooklynDate(f.kickoffUtc) === date &&
          stillToKickOff(f, nowUtcIso) &&
          active.has(f.competition),
      )
      .sort((a, b) => a.kickoffUtc.localeCompare(b.kickoffUtc))
  const tonight = on(today)
  if (tonight.length > 0) return { date: today, slate: tonight, isTonight: true }
  const date = nextMatchday(today, active, fixtures)
  return { date, slate: date ? on(date) : [], isTonight: false }
}

/**
 * The sync timestamp as a Brooklyn calendar date. Everything else in this app is expressed in
 * Beni's local time, so slicing the raw UTC ISO string would show "Aug 24" for a sync that ran
 * on the evening of Aug 23.
 */
export const LAST_SYNC_DATE = zonedParts(new Date(META.lastSyncAt), BROOKLYN_TZ).isoDate

/** The header's provenance stamp — the sync instant, stated in UTC per the templates. */
export const SYNC_STAMP = syncStamp(META.lastSyncAt)

/** Hours since the last successful sync — drives the staleness banner. */
export function hoursSinceSync(now = new Date()): number {
  return hoursSince(META.lastSyncAt, now)
}
