import rawFixtures from '../data/fixtures.json'
import rawMeta from '../data/meta.json'
import { fixturesFileSchema, metaSchema, type Fixture } from './schema'
import { competitionRank, type CompetitionKey } from './competitions'
import { brooklynDate, hoursSince, zonedParts } from './time'
import { BROOKLYN_TZ } from './competitions'

/**
 * Fixture data is validated once at module load. It is generated by `npm run sync`, so a
 * schema failure here means the generator and the app have drifted apart — better to fail
 * loudly at startup than to render half-understood rows.
 */
export const FIXTURES: Fixture[] = fixturesFileSchema.parse(rawFixtures)
export const META = metaSchema.parse(rawMeta)

/**
 * Fixtures are grouped by their *Brooklyn* calendar date, not the stadium's. A 21:00 kickoff
 * in Rome on a Wednesday is still Wednesday evening in Brooklyn, but a 00:30 CET kickoff is
 * the previous day — and the day Beni plans around is his own.
 */
export const BY_DATE: ReadonlyMap<string, Fixture[]> = (() => {
  const map = new Map<string, Fixture[]>()
  for (const f of FIXTURES) {
    const key = brooklynDate(f.kickoffUtc)
    const list = map.get(key)
    if (list) list.push(f)
    else map.set(key, [f])
  }
  for (const list of map.values()) sortForDisplay(list)
  return map
})()

/** Trophies first, then European cups, then domestic leagues; earliest kickoff first within a tier. */
export function sortForDisplay(list: Fixture[]): Fixture[] {
  return list.sort(
    (a, b) =>
      competitionRank(a.competition) - competitionRank(b.competition) ||
      a.kickoffUtc.localeCompare(b.kickoffUtc),
  )
}

export function fixturesOn(date: string, active: ReadonlySet<CompetitionKey>): Fixture[] {
  return (BY_DATE.get(date) ?? []).filter((f) => active.has(f.competition))
}

/** Total on a date regardless of filters — lets the UI say "hidden by filters" vs "nothing on". */
export function totalOn(date: string): number {
  return BY_DATE.get(date)?.length ?? 0
}

export function upcoming(
  fromDate: string,
  active: ReadonlySet<CompetitionKey>,
  limit: number,
): Fixture[] {
  return FIXTURES.filter(
    (f) => brooklynDate(f.kickoffUtc) >= fromDate && active.has(f.competition) && f.status !== 'full_time',
  )
    .sort((a, b) => a.kickoffUtc.localeCompare(b.kickoffUtc))
    .slice(0, limit)
}

/**
 * The sync timestamp as a Brooklyn calendar date. Everything else in this app is expressed in
 * Beni's local time, so slicing the raw UTC ISO string would show "Aug 24" for a sync that ran
 * on the evening of Aug 23.
 */
export const LAST_SYNC_DATE = zonedParts(new Date(META.lastSyncAt), BROOKLYN_TZ).isoDate

/** Hours since the last successful sync — drives the staleness banner. */
export function hoursSinceSync(now = new Date()): number {
  return hoursSince(META.lastSyncAt, now)
}
