import { useCallback } from 'react'
import { COMPETITION_KEYS, COMPETITIONS, type CompetitionKey } from '../lib/competitions'
import { addDays, addMonths, niceDate, shortDate, startOfWeek } from '../lib/time'
import { useUrlState } from '../lib/useUrlState'
import type { Lens } from '../lib/lens'
import { NextUpStrip } from './NextUpStrip'
import { TonightSlate } from './TonightSlate'
import { FilterBar } from './FilterBar'
import { WeekView } from './WeekView'
import { MonthView } from './MonthView'
import { WatchPanel } from './WatchPanel'

const ALL = new Set(COMPETITION_KEYS)

/**
 * The fixtures calendar — everything below the persistent header/tabs when the Fixtures
 * tab is active. Its view state (`view`, `date`, `only`) stays in the URL, so it survives
 * a hop to the Table tab and back.
 */
export function FixturesPage({ today, lens }: { today: string; lens: Lens }) {
  const [view, setView] = useUrlState<'week' | 'month'>(
    'view', 'week',
    (v) => (v === 'week' ? null : v),
    (s) => (s === 'month' ? 'month' : 'week'),
  )
  const [anchor, setAnchor] = useUrlState<string>(
    'date', today,
    (v) => (v === today ? null : v),
    (s) => (/^\d{4}-\d{2}-\d{2}$/.test(s) ? s : today),
  )
  const [active, setActive] = useUrlState<ReadonlySet<CompetitionKey>>(
    'only', ALL,
    (v) => (v.size === COMPETITION_KEYS.length ? null : [...v].join(',')),
    (s) => new Set(s.split(',').filter((k): k is CompetitionKey => k in COMPETITIONS)),
  )

  const onToggle = useCallback(
    (key: CompetitionKey) => {
      const next = new Set(active)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      setActive(next)
    },
    [active, setActive],
  )
  const onSetGroup = useCallback(
    (group: string, on: boolean) => {
      const next = new Set(active)
      for (const k of COMPETITION_KEYS) {
        if (COMPETITIONS[k].group === group) on ? next.add(k) : next.delete(k)
      }
      setActive(next)
    },
    [active, setActive],
  )

  const weekStart = startOfWeek(anchor)
  const monthStart = `${anchor.slice(0, 7)}-01`
  const nav = (dir: number) =>
    setAnchor(view === 'week' ? addDays(anchor, dir * 7) : addMonths(monthStart, dir))

  const periodLabel =
    view === 'week'
      ? `${shortDate(weekStart)} – ${niceDate(addDays(weekStart, 6))}`
      : niceDate(monthStart).replace(/ \d+,/, '')

  return (
    <>
      {/* The hero is the one lens axis that changes the tree: Ledger's Next-up strip,
          Poster's tonight's slate, Broadcast's ticker (mounted under the tab row in App). */}
      {lens === 'poster' ? (
        <TonightSlate today={today} active={active} />
      ) : lens === 'ledger' ? (
        <NextUpStrip today={today} active={active} />
      ) : null}

      <WatchPanel />
      <FilterBar
        active={active}
        onToggle={onToggle}
        onSetGroup={onSetGroup}
        onSetAll={(on) => setActive(on ? ALL : new Set())}
      />

      <div className="mb-3.5 flex gap-2">
        {(['week', 'month'] as const).map((v) => (
          <button
            key={v}
            onClick={() => setView(v)}
            className={[
              'label-caps flex-1 cursor-pointer rounded border-[1.5px] py-2.5 text-[13px]',
              view === v ? 'border-pitch bg-pitch text-white' : 'border-line-strong bg-surface text-ink-secondary',
            ].join(' ')}
          >
            {v === 'week' ? 'Weekly' : 'Monthly'}
          </button>
        ))}
      </div>

      <div className="mb-4 flex items-center justify-between gap-2">
        <button onClick={() => nav(-1)} aria-label="Previous"
          className="size-9 shrink-0 cursor-pointer rounded border-[1.5px] border-line-strong bg-surface">‹</button>
        <div className="flex-1">
          <div className="font-display text-center text-[17px] font-semibold">{periodLabel}</div>
          <button onClick={() => setAnchor(today)}
            className="mt-0.5 w-full cursor-pointer text-center text-[10px] font-semibold tracking-wide text-pitch uppercase">
            Jump to today
          </button>
        </div>
        <button onClick={() => nav(1)} aria-label="Next"
          className="size-9 shrink-0 cursor-pointer rounded border-[1.5px] border-line-strong bg-surface">›</button>
      </div>

      {view === 'week' ? (
        <WeekView weekStart={weekStart} active={active} today={today} lens={lens} />
      ) : (
        <MonthView key={monthStart} monthStart={monthStart} active={active} today={today} />
      )}

      <footer className="mt-8 border-t border-line pt-4 text-[11.5px] leading-relaxed text-ink-muted">
        <div className="label-caps mb-1 text-[10px] text-floodlight">Data</div>
        <p>
          Fixtures are generated by <code className="font-mono">npm run sync</code> from ESPN's
          public fixture API and validated on the way in — they are never hand-edited. Every sync
          diffs against the previous snapshot and reports what moved, so a rescheduled kickoff or
          a swapped home side surfaces instead of rotting. Times shown are the stadium's local
          kickoff and the Brooklyn equivalent, both derived from one stored UTC instant, so they
          cannot drift apart across a DST change.
        </p>
        <p className="mt-2.5">
          Kickoffs marked <i>time not yet set</i> are fixtures where the league has fixed the date
          but not the hour. Always verify in the book before staking.
        </p>
      </footer>
    </>
  )
}
