import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'

export const DIGEST_HEADER = `# Recent sync changes

The latest 30 change-bearing snapshot reports, newest first. An entry on main arrived
with its snapshot; an entry on an open PR is still proposed. This is a reading aid, not
evidence that anyone reviewed a change. Quiet checks add no entry. Older entries remain
in Git history; full logs follow the repository's Actions retention policy.

Generated by scripts/sync-digest.ts. Do not edit entries by hand.
`
const MARKER = /^<!-- kickoff-sync-entry: (\d+) -->$/gm

export function updateDigest(previous: string, log: string, runId: string, repository: string, stamp: string): string {
  if (!/^\d+$/.test(runId) || !/^[\w.-]+\/[\w.-]+$/.test(repository) || !stamp || /[\r\n<>]/.test(stamp)) {
    throw new Error('Invalid digest provenance')
  }
  const matches = [...previous.matchAll(MARKER)]
  if (previous && !previous.startsWith(DIGEST_HEADER)) throw new Error('Unrecognised sync digest; refusing to replace it')
  const oldEntries = matches.map((m, i) => ({
    id: m[1], text: previous.slice(m.index!, matches[i + 1]?.index).trimEnd(),
  })).filter((entry) => entry.id !== runId)
  const clean = log.replace(/[\u0000-\u0008\u000b-\u001f\u007f]/g, '')
  const excerpt = clean.slice(0, 32_000).split('\n').slice(0, 400).join('\n')
  const clipped = excerpt.length < clean.length
  // Indentation keeps provider names, HTML, fences and apparent entry markers inside code.
  const text = excerpt.split('\n').map((line) => `    ${line}`).join('\n')
  const entry = `<!-- kickoff-sync-entry: ${runId} -->\n## ${stamp}\n\n[Full sync log](https://github.com/${repository}/actions/runs/${runId})\n\n${text}${clipped ? '\n\nReport excerpt truncated; use the full sync log above.' : ''}`
  return DIGEST_HEADER + '\n' + [entry, ...oldEntries.slice(0, 29).map((e) => e.text)].join('\n\n') + '\n'
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const path = 'docs/sync-digest.md'
  const next = updateDigest(
    existsSync(path) ? readFileSync(path, 'utf8') : '', readFileSync('sync-output.txt', 'utf8'),
    process.env.GITHUB_RUN_ID ?? '', process.env.GITHUB_REPOSITORY ?? '', process.env.SYNC_STAMP ?? '',
  )
  writeFileSync(path, next)
}
